using Content.Client._Lua.Styles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Lua.VendingMachines.UI;

[GenerateTypedNameReferences]
public sealed partial class LuaVendingEntry : Control
{
    public LuaVendingEntry()
    {
        RobustXamlLoader.Load(this);
        Price.FontOverride = LunaWindowStyle.FontSmall;
        Amount.FontOverride = LunaWindowStyle.FontSmall;
        Panel.Title.FontOverride = LunaWindowStyle.FontBody;
        SetDisabled(false);
    }

    public void SetDisabled(bool disabled)
    {
        Panel.Button.Disabled = disabled;
        Amount.FontColorOverride = disabled ? LunaWindowStyle.AccentBad : LunaWindowStyle.TextSecondary;
        Price.FontColorOverride = disabled ? LunaWindowStyle.TextMuted : LunaWindowStyle.Accent;
        Panel.Title.FontColorOverride = disabled ? LunaWindowStyle.TextMuted : LunaWindowStyle.TextPrimary;
        Panel.UpdateColor();
    }
}
