using Content.Client._Lua.Styles;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Lua.VendingMachines.UI;

[GenerateTypedNameReferences]
public sealed partial class LuaVendingPanel : Control
{
    private static readonly Color HoveredBg = Color.FromHex("#163040");
    private static readonly Color DisabledBg = Color.FromHex("#1C2433");

    public Color BorderColor = LunaWindowStyle.PanelBorder;
    public Color HoveredColor = LunaWindowStyle.Accent;

    public LuaVendingPanel()
    {
        RobustXamlLoader.Load(this);
        Button.OnDrawModeChanged += UpdateColor;

        Title.ScrollEnabled = false;
        Button.OnMouseEntered += _ => Title.ScrollEnabled = true;
        Button.OnMouseExited += _ => Title.ScrollEnabled = false;

        UpdateColor();
    }

    public void UpdateColor()
    {
        var panel = (StyleBoxFlat) Panel.PanelOverride!;
        if (Button.Disabled)
        {
            panel.BackgroundColor = DisabledBg;
            panel.BorderColor = LunaWindowStyle.TextMuted;
            return;
        }

        panel.BackgroundColor = Button.IsHovered ? HoveredBg : LunaWindowStyle.PanelBg;
        panel.BorderColor = Button.IsHovered ? HoveredColor : BorderColor;
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        UpdateColor();
    }
}
