using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Client._NF.Shipyard.BUI;
using Content.Shared._NF.Bank;
using Content.Shared._NF.Shipyard.BUI;
using Content.Shared._NF.Shipyard.Prototypes;
using Content.Shared.Shuttles.BUIStates; // Lua
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map; // Lua
using Robust.Shared.Prototypes;
using static Robust.Client.UserInterface.Controls.BaseButton;

namespace Content.Client._NF.Shipyard.UI;

[GenerateTypedNameReferences]
public sealed partial class ShipyardConsoleMenu : FancyWindow
{
    [Dependency] private IPrototypeManager _protoManager = default!;
    [Dependency] private IEntityManager _entManager = default!; // Lua
    public event Action<ButtonEventArgs>? OnSellShip;
    public event Action<VesselPrototype>? OnOrderApproved; // Lua: ButtonEventArgs > VesselPrototype
    public event Action<ButtonEventArgs>? OnUnassignDeed;
    public event Action<string>? OnRenameShip;
    public event Action<VesselPrototype>? OnPreviewShip; // Lua: ButtonEventArgs > VesselPrototype
    public event Action<NetEntity?>? OnDockPortSelected; // Lua
    private readonly ShipyardConsoleBoundUserInterface _menu;
    private readonly List<VesselSize> _categoryStrings = new();
    private readonly List<VesselClass> _classStrings = new();
    private readonly List<VesselEngine> _engineStrings = new();
    private VesselSize? _category;
    private VesselClass? _class;
    private VesselEngine? _engine;

    private List<string> _lastAvailableProtos = new();
    private List<string> _lastUnavailableProtos = new();
    private bool _freeListings = false;
    private bool _validId = false;

    // Lua start
    private const float MaxDockPickDistance = 4.0f;

    private readonly SharedTransformSystem _xform;
    private NavInterfaceState? _dockNav;
    private NetEntity? _selectedDockPort;
    private Dictionary<ProtoId<VesselPrototype>, int> _limitedCounts = new();
    private bool _hyperwarLimits;
    private ConfirmButton? _currentlyConfirmingButton;
    // Lua end

    public ShipyardConsoleMenu(ShipyardConsoleBoundUserInterface owner)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _menu = owner;
        _xform = _entManager.System<SharedTransformSystem>(); // Lua
        Title = Loc.GetString("shipyard-console-menu-title");
        SearchBar.OnTextChanged += OnSearchBarTextChanged;
        Categories.OnItemSelected += OnCategoryItemSelected;
        Classes.OnItemSelected += OnClassItemSelected;
        Engines.OnItemSelected += OnEngineItemSelected;
        SellShipButton.OnPressed += (args) => { OnSellShip?.Invoke(args); };
        UnassignDeedButton.OnPressed += (args) => { OnUnassignDeed?.Invoke(args); };
        RenameButton.OnPressed += OnRenameButtonPressed;
        DockRadar.OnRadarClick += OnDockRadarClick; // Lua
    }

    // Lua start
    public void UpdateDockSelect(NavInterfaceState? nav, NetEntity? selectedPort)
    {
        _dockNav = nav;
        _selectedDockPort = nav == null ? null : selectedPort;
        DockRadar.HighlightDockPort = _selectedDockPort;

        if (nav != null)
            DockRadar.UpdateState(nav);
    }

    /// <summary>
    /// Selects the docking port closest to the click, or clears the selection when clicking the selected one or empty space.
    /// </summary>
    private void OnDockRadarClick(EntityCoordinates coords)
    {
        if (_dockNav == null)
            return;

        var clickMapPos = _xform.ToMapCoordinates(coords).Position;
        NetEntity? best = null;
        var bestDistSq = float.MaxValue;

        foreach (var ports in _dockNav.Docks.Values)
        {
            foreach (var port in ports)
            {
                var portCoords = _entManager.GetCoordinates(port.Coordinates);
                if (!portCoords.IsValid(_entManager))
                    continue;

                var distSq = (_xform.ToMapCoordinates(portCoords).Position - clickMapPos).LengthSquared();
                if (distSq >= bestDistSq)
                    continue;

                bestDistSq = distSq;
                best = port.Entity;
            }
        }

        if (best == null || bestDistSq > MaxDockPickDistance * MaxDockPickDistance || best == _selectedDockPort)
            best = null;

        _selectedDockPort = best;
        DockRadar.HighlightDockPort = best;
        OnDockPortSelected?.Invoke(best);
    }
    // Lua end

    private void OnCategoryItemSelected(OptionButton.ItemSelectedEventArgs args)
    {
        SetCategoryText(args.Id);
        PopulateProducts(_lastAvailableProtos, _lastUnavailableProtos, _freeListings, _validId);
    }

    private void OnClassItemSelected(OptionButton.ItemSelectedEventArgs args)
    {
        SetClassText(args.Id);
        PopulateProducts(_lastAvailableProtos, _lastUnavailableProtos, _freeListings, _validId);
    }

    private void OnEngineItemSelected(OptionButton.ItemSelectedEventArgs args)
    {
        SetEngineText(args.Id);
        PopulateProducts(_lastAvailableProtos, _lastUnavailableProtos, _freeListings, _validId);
    }

    private void OnRenameButtonPressed(ButtonEventArgs args)
    {
        var newName = RenameLineEdit.Text.Trim();
        if (string.IsNullOrEmpty(newName))
            return;

        // Validate length (30 characters max, matching ShuttleDeedComponent.MaxNameLength)
        if (newName.Length > 30)
        {
            newName = newName[..30];
        }

        OnRenameShip?.Invoke(newName);
        RenameLineEdit.Text = "";
    }

    private void OnSearchBarTextChanged(LineEdit.LineEditEventArgs args)
    {
        PopulateProducts(_lastAvailableProtos, _lastUnavailableProtos, _freeListings, _validId);
    }

    private void SetCategoryText(int id)
    {
        _category = id == 0 ? null : _categoryStrings[id];
        Categories.SelectId(id);
    }
    private void SetClassText(int id)
    {
        _class = id == 0 ? null : _classStrings[id];
        Classes.SelectId(id);
    }
    private void SetEngineText(int id)
    {
        _engine = id == 0 ? null : _engineStrings[id];
        Engines.SelectId(id);
    }

    // Lua start
    /// <summary>
    /// Stores the active shuttle counts used to show limits in the list.
    /// </summary>
    public void SetLimitedCounts(Dictionary<ProtoId<VesselPrototype>, int> limitedCounts, bool hyperwarLimits)
    {
        _limitedCounts = limitedCounts;
        _hyperwarLimits = hyperwarLimits;
    }
    // Lua end

    /// <summary>
    ///     Populates the list of products that will actually be shown, using the current filters.
    /// </summary>
    public void PopulateProducts(List<string> availablePrototypes, List<string> unavailablePrototypes, bool free, bool canPurchase)
    {
        Vessels.RemoveAllChildren();
        _currentlyConfirmingButton = null; // Lua

        var search = SearchBar.Text.Trim().ToLowerInvariant();

        var newVessels = GetVesselPrototypesFromIds(availablePrototypes);
        AddVesselsToControls(newVessels, search, free, canPurchase);

        var newUnavailableVessels = GetVesselPrototypesFromIds(unavailablePrototypes);
        AddVesselsToControls(newUnavailableVessels, search, free, false);

        _lastAvailableProtos = availablePrototypes;
        _lastUnavailableProtos = unavailablePrototypes;
    }

    /// <summary>
    /// Given a set of prototype IDs, returns a corresponding set of prototypes, ordered by name.
    /// </summary>
    private List<VesselPrototype> GetVesselPrototypesFromIds(IEnumerable<string> protoIds) // Lua: VesselPrototype? > VesselPrototype
    {
        var vesselList = protoIds.Select(it => _protoManager.TryIndex<VesselPrototype>(it, out var proto) ? proto : null)
            .OfType<VesselPrototype>() // Lua: Where(it => it != null) > OfType
            .ToList();

        vesselList.Sort((x, y) =>
            string.Compare(GetLocalizedVesselName(x), GetLocalizedVesselName(y), StringComparison.CurrentCultureIgnoreCase)); // Lua: Name > GetLocalizedVesselName
        return vesselList;
    }

    /// <summary>
    /// Adds all vessels in a given list of prototypes as VesselRows in the UI.
    /// </summary>
    private void AddVesselsToControls(IEnumerable<VesselPrototype> vessels, string search, bool free, bool canPurchase)
    {
        foreach (var prototype in vessels)
        {
            // Filter any ships
            if (_category != null && !prototype.Category.Equals(_category))
                continue;
            if (_class != null && !prototype.Classes.Contains(_class.Value))
                continue;
            if (_engine != null && !prototype.Engines.Contains(_engine.Value))
                continue;
// LuaM-start:
            if (search.Length > 0)
            {
                var localizedName = GetLocalizedVesselName(prototype).ToLowerInvariant();
                var protoId = prototype.ID.ToLowerInvariant();

                if (!localizedName.Contains(search) && !protoId.Contains(search))
                    continue;
            }
// LuaM-end.
            string priceText;
            if (free)
                priceText = Loc.GetString("shipyard-console-menu-listing-free");
            else if (!prototype.Purchasable) // Mono
                priceText = Loc.GetString("shipyard-console-menu-listing-voucher");
            else
                priceText = BankSystemExtensions.ToSpesoString(prototype.Price);

            // Lua start
            var limit = _hyperwarLimits ? prototype.HyperwarLimitActive : prototype.LimitActive;
            var limitRemain = limit - _limitedCounts.GetValueOrDefault((ProtoId<VesselPrototype>) prototype.ID);
            var purchaseDisabled = !canPurchase || limit > 0 && limitRemain <= 0;
            // Lua end

            var vesselEntry = new VesselRow
            {
                Vessel = prototype,
                VesselName = { Text = GetLocalizedVesselName(prototype) }, // LuaM
                // Lua start
                CategoryLabel = { Text = Loc.GetString($"shipyard-console-category-{prototype.Category}") },
                LimitedCount = { Visible = limit > 0, Text = $"{Math.Max(limitRemain, 0)}/{limit}" },
                Purchase = { Disabled = purchaseDisabled },
                Preview = { TooltipDelay = 0.2f, ToolTip = GetLocalizedVesselDescription(prototype) },
                // Lua end
                Price = { Text = priceText },
            };
            vesselEntry.Purchase.OnConfirming += OnStartConfirmingPurchase; // Lua
            vesselEntry.Purchase.OnPressed += _ =>
            {
                _currentlyConfirmingButton = null; // Lua
                OnOrderApproved?.Invoke(prototype);
            };
            vesselEntry.Preview.OnPressed += _ => OnPreviewShip?.Invoke(prototype);
            Vessels.AddChild(vesselEntry);
        }
    }

    // Lua start
    /// <summary>
    /// Ensures that only one purchase button is waiting for confirmation at a time.
    /// </summary>
    private void OnStartConfirmingPurchase(ButtonEventArgs args)
    {
        if (args.Button is not ConfirmButton confirmButton)
            return;

        if (_currentlyConfirmingButton != null && _currentlyConfirmingButton != confirmButton)
            _currentlyConfirmingButton.ClearIsConfirming();

        _currentlyConfirmingButton = confirmButton;
    }
    // Lua end

    /// <summary>
    ///     Populates the list categories that will actually be shown, using the current filters.
    /// </summary>
    public void PopulateCategories(List<string> availablePrototypes, List<string> unavailablePrototypes)
    {
        _categoryStrings.Clear();
        Categories.Clear();

        AddCategoriesFromPrototypes(availablePrototypes);
        AddCategoriesFromPrototypes(unavailablePrototypes);

        _categoryStrings.Sort();

        // Add "All" category at the top of the list
        _categoryStrings.Insert(0, VesselSize.All);

        foreach (var str in _categoryStrings)
        {
            Categories.AddItem(Loc.GetString($"shipyard-console-category-{str}"));
        }
    }

    /// <summary>
    /// Adds all ship categories from a list of vessel prototypes to the current control's list if they are missing.
    /// </summary>
    private void AddCategoriesFromPrototypes(IEnumerable<string> prototypes)
    {
        foreach (var protoId in prototypes)
        {
            if (!_protoManager.TryIndex<VesselPrototype>(protoId, out var prototype))
                continue;

            if (!_categoryStrings.Contains(prototype.Category) && prototype.Category != VesselSize.All)
            {
                _categoryStrings.Add(prototype.Category);
            }
        }
    }

    /// <summary>
    ///     Populates the list classes that will actually be shown, using the current filters.
    /// </summary>
    public void PopulateClasses(List<string> availablePrototypes, List<string> unavailablePrototypes)
    {
        _classStrings.Clear();
        Classes.Clear();

        AddClassesFromPrototypes(availablePrototypes);
        AddClassesFromPrototypes(unavailablePrototypes);

        _classStrings.Sort();

        // Add "All" category at the top of the list
        _classStrings.Insert(0, VesselClass.All);

        foreach (var str in _classStrings)
        {
            Classes.AddItem(Loc.GetString($"shipyard-console-class-{str}"));
        }
    }

    /// <summary>
    /// Adds all ship classes from a list of vessel prototypes to the current control's list if they are missing.
    /// </summary>
    private void AddClassesFromPrototypes(IEnumerable<string> prototypes)
    {
        foreach (var protoId in prototypes)
        {
            if (!_protoManager.TryIndex<VesselPrototype>(protoId, out var prototype))
                continue;

            foreach (var cl in prototype.Classes)
            {
                if (!_classStrings.Contains(cl) && cl != VesselClass.All)
                {
                    _classStrings.Add(cl);
                }
            }
        }
    }

    /// <summary>
    ///     Populates the list engines that will actually be shown, using the current filters.
    /// </summary>
    public void PopulateEngines(List<string> availablePrototypes, List<string> unavailablePrototypes)
    {
        _engineStrings.Clear();
        Engines.Clear();

        AddEnginesFromPrototypes(availablePrototypes);
        AddEnginesFromPrototypes(unavailablePrototypes);

        _engineStrings.Sort();

        // Add "All" category at the top of the list
        _engineStrings.Insert(0, VesselEngine.All);

        foreach (var str in _engineStrings)
        {
            Engines.AddItem(Loc.GetString($"shipyard-console-engine-{str}"));
        }
    }

    /// <summary>
    /// Adds all ship engine power type from a list of vessel prototypes to the current control's list if they are missing.
    /// </summary>
    private void AddEnginesFromPrototypes(IEnumerable<string> prototypes)
    {
        foreach (var protoId in prototypes)
        {
            if (!_protoManager.TryIndex<VesselPrototype>(protoId, out var prototype))
                continue;

            foreach (var cl in prototype.Engines)
            {
                if (!_engineStrings.Contains(cl) && cl != VesselEngine.All)
                {
                    _engineStrings.Add(cl);
                }
            }
        }
    }

    public void UpdateState(ShipyardConsoleInterfaceState state)
    {
        BalanceLabel.Text = BankSystemExtensions.ToSpesoString(state.Balance);
        var shipPrice = 0;
        if (!state.FreeListings)
            shipPrice = state.ShipSellValue;

        ShipAppraisalLabel.Text = $"{BankSystemExtensions.ToSpesoString(shipPrice)} ({state.SellRate * 100.0f:F1}%)";
        SellShipButton.Disabled = state.ShipDeedTitle == null;
        UnassignDeedButton.Disabled = state.ShipDeedTitle == null;

        // Show/hide and enable/disable rename controls based on whether there's a ship deed
        var hasShipDeed = state.ShipDeedTitle != null;
        RenameContainer.Visible = hasShipDeed;
        RenameLineEdit.Editable = hasShipDeed;
        RenameButton.Disabled = !hasShipDeed;

        TargetIdButton.Text = state.IsTargetIdPresent
            ? Loc.GetString("id-card-console-window-eject-button")
            : Loc.GetString("id-card-console-window-insert-button");
        NoDeedHelperContainer.Visible = !state.IsTargetIdPresent; // Lua
        if (state.ShipDeedTitle != null)
        {
            DeedTitle.Text = state.ShipDeedTitle;
        }
        else
        {
            DeedTitle.Text = Loc.GetString("shipyard-console-deed-label-none"); // Lua: shipyard-console-no-deed > shipyard-console-deed-label-none
        }
        _freeListings = state.FreeListings;
        _validId = state.IsTargetIdPresent;
        PopulateProducts(_lastAvailableProtos, _lastUnavailableProtos, _freeListings, _validId);
    }

// LuaM-start:
    /// <summary>
    /// Getting localized shuttle name
    /// </summary>
    private string GetLocalizedVesselName(VesselPrototype vessel)
    {
        if (!string.IsNullOrEmpty(vessel.LocName))
            return Loc.GetString(vessel.LocName);

        if (!string.IsNullOrEmpty(vessel.Name) && vessel.Name.StartsWith("vessel-"))
            return Loc.GetString(vessel.Name);

        return vessel.Name;
    }

    /// <summary>
    /// Getting localized shuttle description
    /// </summary>
    private string GetLocalizedVesselDescription(VesselPrototype vessel)
    {
        if (!string.IsNullOrEmpty(vessel.LocDescription))
            return Loc.GetString(vessel.LocDescription);

        if (!string.IsNullOrEmpty(vessel.Description) && vessel.Description.StartsWith("vessel-"))
            return Loc.GetString(vessel.Description);

        return vessel.Description;
    }
// LuaM-end.
}
