using System.Linq;
using Content.Client._Lua.Styles;
using Content.Client._Lua.VendingMachines.UI;
using Content.Shared._NF.Bank;
using Content.Shared.Cargo.Components;
using Content.Shared.Chemistry.Components.SolutionManager;
using Content.Shared.Chemistry.Reagent;
using Content.Shared.Stacks;
using Content.Shared.VendingMachines;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Lua.VendingMachines;

[GenerateTypedNameReferences]
public sealed partial class LuaVendingMachineWindow : LunaWindow
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    [Dependency] private IComponentFactory _componentFactory = default!;

    private readonly List<((InventoryType Type, string Id) Key, LuaVendingEntry Row)> _rows = new();

    public event Action<InventoryType, string>? OnItemSelected;

    public LuaVendingMachineWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        ApplyLunaChrome();

        Shell.PanelOverride = LunaWindowStyle.Shell();
        LunaWindowStyle.StyleDivider(HeaderDivider);
        LunaWindowStyle.StyleDivider(FooterDivider);
        LunaWindowStyle.StyleMuted(BalanceCaption);
        LunaWindowStyle.StyleValue(BalanceLabel);
        LunaWindowStyle.StyleMuted(CashSlotCaption);
        LunaWindowStyle.StyleValue(CashSlotLabel);
        LunaWindowStyle.StyleSecondary(SearchLabel);
        LunaWindowStyle.StyleMuted(EmptyLabel);
        LunaWindowStyle.StyleFooter(FlavorLeft);
        LunaWindowStyle.StyleFooter(FlavorRight);

        Search.OnTextChanged += args => ApplySearchFilter(args.Text);
    }

    public void Populate(List<VendingMachineInventoryEntry> inventory,
        bool enabled,
        float priceModifier,
        int balance,
        int? cashSlotBalance,
        bool requiresCash)
    {
        UpdateBalance(balance);
        UpdateCashSlotBalance(cashSlotBalance);

        var hasItems = inventory.Count > 0;
        Search.Visible = hasItems;
        SearchLabel.Visible = hasItems;
        CatalogScroll.Visible = hasItems;
        EmptyLabel.Visible = !hasItems;

        if (SameItems(inventory))
        {
            for (var i = 0; i < inventory.Count; i++)
            {
                if (_prototypeManager.TryIndex<EntityPrototype>(inventory[i].ID, out var prototype))
                    ApplyRowState(_rows[i].Row, inventory[i], prototype, enabled, priceModifier, requiresCash);
            }

            return;
        }

        _rows.Clear();
        Entries.DisposeAllChildren();

        foreach (var entry in inventory)
        {
            if (!_prototypeManager.TryIndex<EntityPrototype>(entry.ID, out var prototype))
                continue;

            var row = CreateRow(entry, prototype);
            ApplyRowState(row, entry, prototype, enabled, priceModifier, requiresCash);
            _rows.Add(((entry.Type, entry.ID), row));
            Entries.AddChild(row);
        }

        ApplySearchFilter(Search.Text);
    }

    public void UpdateBalance(int balance)
    {
        BalanceLabel.Text = BankSystemExtensions.ToSpesoString(balance);
    }

    public void UpdateCashSlotBalance(int? balance)
    {
        CashSlotControls.Visible = balance != null;
        if (balance != null)
            CashSlotLabel.Text = BankSystemExtensions.ToSpesoString(balance.Value);
    }

    private bool SameItems(List<VendingMachineInventoryEntry> inventory)
    {
        if (_rows.Count != inventory.Count)
            return false;

        for (var i = 0; i < inventory.Count; i++)
        {
            if (_rows[i].Key != (inventory[i].Type, inventory[i].ID))
                return false;
        }

        return true;
    }

    private LuaVendingEntry CreateRow(VendingMachineInventoryEntry entry, EntityPrototype prototype)
    {
        var row = new LuaVendingEntry();
        row.Icon.SetPrototype(prototype.ID);
        row.Panel.Title.Text = prototype.Name;

        switch (entry.Type)
        {
            case InventoryType.Emagged:
                row.Panel.BorderColor = LunaWindowStyle.AccentBad;
                row.Panel.HoveredColor = LunaWindowStyle.AccentBad;
                break;
            case InventoryType.Contraband:
                row.Panel.BorderColor = LunaWindowStyle.AccentWarn;
                row.Panel.HoveredColor = LunaWindowStyle.AccentWarn;
                break;
        }

        var name = prototype.Name;
        var description = prototype.Description;
        row.Panel.Button.TooltipDelay = 0;
        row.Panel.Button.TooltipSupplier = _ =>
        {
            var tooltipText = new FormattedMessage();
            tooltipText.AddText(name);
            if (!string.IsNullOrWhiteSpace(description))
            {
                tooltipText.PushNewline();
                tooltipText.AddText(description);
            }

            var tooltip = new Tooltip();
            tooltip.SetMessage(tooltipText);
            return tooltip;
        };

        var type = entry.Type;
        var id = entry.ID;
        row.Panel.Button.OnPressed += _ => OnItemSelected?.Invoke(type, id);
        return row;
    }

    private void ApplyRowState(LuaVendingEntry row,
        VendingMachineInventoryEntry entry,
        EntityPrototype prototype,
        bool enabled,
        float priceModifier,
        bool requiresCash)
    {
        var cost = requiresCash ? GetPrice(prototype, priceModifier) : 0; // Mono: free vending shows no price
        row.Price.Text = BankSystemExtensions.ToSpesoString(cost);
        row.Amount.Text = entry.Amount == uint.MaxValue ? string.Empty : entry.Amount.ToString(); // Frontier: unlimited vending
        row.SetDisabled(!enabled || entry.Amount == 0);
    }

    private void ApplySearchFilter(string? text)
    {
        foreach (var (_, row) in _rows)
        {
            row.Visible = string.IsNullOrWhiteSpace(text) ||
                          (row.Panel.Title.Text?.Contains(text, StringComparison.CurrentCultureIgnoreCase) ?? false);
        }
    }

    private int GetPrice(EntityPrototype prototype, float priceModifier)
    {
        var vendPrice = 0.0;
        if (prototype.TryGetComponent<StaticPriceComponent>(out var staticVend, _componentFactory) && staticVend.VendPrice > 0.0)
            vendPrice = staticVend.VendPrice;
        else if (prototype.TryGetComponent<StackPriceComponent>(out var stackVend, _componentFactory) && stackVend.VendPrice > 0.0)
            vendPrice = stackVend.VendPrice;

        if (vendPrice > 0.0)
            return (int) vendPrice;

        var cost = 20;
        if (prototype.TryGetComponent<StaticPriceComponent>(out var priceComponent, _componentFactory))
        {
            if (priceComponent.Price != 0)
                cost = (int) ((float) priceComponent.Price * priceModifier);
            else if (prototype.TryGetComponent<StackPriceComponent>(out var stackPrice, _componentFactory)
                     && prototype.TryGetComponent<StackComponent>(out var stack, _componentFactory))
                cost = (int) (stackPrice.Price * stack.Count * priceModifier);
            else
                cost = (int) (cost * priceModifier);
        }
        else
        {
            cost = (int) (cost * priceModifier);
        }

        if (prototype.TryGetComponent<SolutionContainerManagerComponent>(out var solutions, _componentFactory)
            && solutions.Solutions != null)
        {
            foreach (var solution in solutions.Solutions.Values)
            {
                foreach (var (reagent, quantity) in solution.Contents)
                {
                    if (_prototypeManager.TryIndex<ReagentPrototype>(reagent.Prototype, out var reagentProto))
                        cost += (int) (quantity.Float() * reagentProto.PricePerUnit * priceModifier);
                }
            }
        }

        return cost;
    }
}
