using Content.Client.UserInterface.Controls;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Utility;

namespace Content.Client._LuaM.WarDeclaration;

/// <summary>
/// Asks for the reason of the war before it is declared from the communications console.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class WarDeclarationWindow : FancyWindow
{
    [Dependency] private IConfigurationManager _cfg = default!;

    public event Action<string>? OnConfirm;

    public WarDeclarationWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        ReasonInput.Placeholder = new Rope.Leaf(Loc.GetString("comms-console-war-declaration-window-placeholder"));

        var maxLength = _cfg.GetCVar(CCVars.ChatMaxAnnouncementLength);
        ReasonInput.OnTextChanged += args =>
        {
            var length = args.Control.TextLength;
            ConfirmButton.Disabled = length == 0 || length > maxLength ||
                                     string.IsNullOrWhiteSpace(Rope.Collapse(ReasonInput.TextRope));
        };

        CancelButton.OnPressed += _ => Close();
        ConfirmButton.OnPressed += _ =>
        {
            OnConfirm?.Invoke(Rope.Collapse(ReasonInput.TextRope));
            Close();
        };
    }
}
