using Content.Shared._LuaM.Yupi;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._LuaM.Yupi;

[GenerateTypedNameReferences]
public sealed partial class YupiUiFragment : BoxContainer
{
    [Dependency] private IClipboardManager _clipboard = default!;
    [Dependency] private IGameTiming _timing = default!;

    private static readonly Color HintColor = Color.FromHex("#A0A0A0");

    public event Action<string, int>? OnSend;

    private int _balance;
    private int _lowRateRemaining;
    private TimeSpan _nextTransfer;

    private int _shownCooldownSeconds = -1;

    public YupiUiFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        CodeInput.IsValid = text => text.Length <= YupiRules.CodeLength;
        AmountInput.IsValid = text => text.Length == 0 || TryParseAmount(text, out var value) && value >= 0;

        CodeInput.OnTextChanged += _ => UpdatePreview();
        AmountInput.OnTextChanged += _ => UpdatePreview();

        CopyCodeButton.OnPressed += _ =>
        {
            if (YupiRules.IsValidCode(CopyCodeButton.Text ?? string.Empty))
                _clipboard.SetText(CopyCodeButton.Text!);
        };

        SendButton.OnPressed += _ =>
        {
            if (TryGetInput(out var code, out var amount))
                OnSend?.Invoke(code, amount);
        };

        UpdatePreview();
    }

    public void UpdateState(YupiUiState state)
    {
        var hasAccount = state.OwnCode != string.Empty;
        NoAccountLabel.Visible = !hasAccount;
        AccountBox.Visible = hasAccount;

        CopyCodeButton.Text = hasAccount ? state.OwnCode : "------";
        BalanceLabel.Text = Loc.GetString("yupi-ui-credits", ("amount", YupiRules.FormatCredits(state.Balance)));
        LowRateLabel.Text = Loc.GetString("yupi-ui-credits", ("amount", YupiRules.FormatCredits(state.LowRateRemaining)));
        _balance = state.Balance;
        _lowRateRemaining = state.LowRateRemaining;
        _nextTransfer = state.NextTransfer;
        _shownCooldownSeconds = -1;
        UpdatePreview();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        var seconds = GetCooldownSeconds();
        if (seconds == _shownCooldownSeconds)
            return;

        _shownCooldownSeconds = seconds;
        UpdateSendButton();
    }

    private void UpdatePreview()
    {
        string text;
        if (!TryParseAmount(AmountInput.Text, out var amount) || amount <= 0)
        {
            text = Loc.GetString("yupi-ui-commission-hint",
                ("low", YupiRules.LowRatePercent),
                ("high", YupiRules.HighRatePercent));
        }
        else
        {
            var commission = YupiRules.GetCommission(amount, _lowRateRemaining);
            text = Loc.GetString("yupi-ui-commission-preview",
                ("commission", YupiRules.FormatCredits(commission)),
                ("net", YupiRules.FormatCredits(amount - commission)));
        }

        CommissionLabel.SetMessage(FormattedMessage.FromUnformatted(text), HintColor);
        UpdateSendButton();
    }

    private void UpdateSendButton()
    {
        var seconds = GetCooldownSeconds();
        SendButton.Text = seconds > 0
            ? Loc.GetString("yupi-ui-send-cooldown", ("time", $"{seconds / 60}:{seconds % 60:D2}"))
            : Loc.GetString("yupi-ui-send");
        SendButton.Disabled = seconds > 0 || !TryGetInput(out _, out _);
    }

    private int GetCooldownSeconds()
    {
        var remaining = _nextTransfer - _timing.CurTime;
        return remaining > TimeSpan.Zero ? (int) Math.Ceiling(remaining.TotalSeconds) : 0;
    }

    private bool TryGetInput(out string code, out int amount)
    {
        code = YupiRules.NormalizeCode(CodeInput.Text);
        return TryParseAmount(AmountInput.Text, out amount)
               && amount > 0
               && amount <= _balance
               && amount > YupiRules.GetCommission(amount, _lowRateRemaining)
               && YupiRules.IsValidCode(code);
    }

    private static bool TryParseAmount(string text, out int amount)
    {
        return int.TryParse(text.Replace(".", string.Empty), out amount);
    }
}
